select FATORPRODUCAO.DESIGNACAO as FATORPRODUCAO,
count(FATORPRODUCAO.APLICACAO) as NUMERO_APLICACOES
from operacao
inner join FATORPRODUCAO on OPERACAO.FATORPRODUCAODESIGNACAO = FATORPRODUCAO.DESIGNACAO
where OPERACAO.DATA between date '2021-12-06' and date '2023-08-24'
group by FATORPRODUCAO.DESIGNACAO